-- Retorna cargo de um funcionário dado o CPF.
CREATE FUNCTION GET_CARGO(key CHAR(14))
    RETURNS VARCHAR AS $$
    DECLARE
        VALOR VARCHAR(14);
    BEGIN
        SELECT CARGO INTO VALOR FROM FUNCIONARIO WHERE (CPF = key);
        IF VALOR = 'AGENTE' THEN
            SELECT TIPO INTO VALOR FROM AGENTE WHERE (CPF = key);
        END IF;
        RETURN VALOR;
    END;
$$  LANGUAGE plpgsql;


CREATE TABLE FUNCIONARIO (
    CPF CHAR(14) NOT NULL,
    NOME VARCHAR(40),
    TELEFONE VARCHAR(15),
    CARGO VARCHAR(8),
    SALARIO INT,
    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (CPF),
    CONSTRAINT CK_CPF CHECK (CPF ~ '[0-9]{3}\.[0-9]{3}\.[0-9]{3}\-[0-9]{2}$'),
    CONSTRAINT CK_TELEFONE CHECK (TELEFONE ~ '^\([1-9]{2}\) (?:[2-8]|9[1-9])[0-9]{3}\-[0-9]{4}$'),
    CONSTRAINT CK_CARGO CHECK ((CARGO) IN ('ESCUTA', 'REDATOR', 'PRODUTOR', 'EDITOR', 'AGENTE'))
);


CREATE TABLE AGENTE (
    CPF CHAR(14) NOT NULL,
    TIPO VARCHAR(12),
    SALARIOEXTRA INT,
    CONSTRAINT PK_AGENTE PRIMARY KEY (CPF),
    CONSTRAINT FK_AGENTE FOREIGN KEY (CPF) REFERENCES FUNCIONARIO (CPF) ON DELETE CASCADE,
    CONSTRAINT CK_AGENTE CHECK (GET_CARGO(CPF) IN ('AGENTE')),
    CONSTRAINT CK_TIPO CHECK ((TIPO) IN ('APRESENTADOR', 'CAMERAMAN_E', 'CAMERAMAN_C', 'AUXILIAR_E', 'AUXILIAR_C', 'REPORTER', 'MOTORISTA'))
);


CREATE TABLE ACONTECIMENTO (
    NOME VARCHAR(100) NOT NULL,
    DATA DATE NOT NULL,
    HORA TIME,
    DESCRICAO TEXT,
    MEMBROEQUIPEESCUTA CHAR(14),
    CONSTRAINT PK_ACONTECIMENTO PRIMARY KEY (NOME, DATA),
    CONSTRAINT FK_ACONTECIMENTO FOREIGN KEY (MEMBROEQUIPEESCUTA) REFERENCES FUNCIONARIO (CPF) ON DELETE SET NULL,
    CONSTRAINT CK_ESCUTA CHECK (GET_CARGO(MEMBROEQUIPEESCUTA) IN ('ESCUTA'))
);
-- membroequipeescuta ta como NOT NULL no esquema, mas a gente nao quer perder registros se um
-- funcionario ser demitido né? (ou podemos setar um valor default que represente funcionario demitido, o que preferem?).


CREATE TABLE NOTICIA (
    TITULO VARCHAR(200) NOT NULL,
    DATA DATE NOT NULL,
    CATEGORIA VARCHAR(20),
    DESCRICAO TEXT,
    NOMEACONT VARCHAR(100),
    DATAACONT DATE,
    REDATOR CHAR(14),
    PRODUTOR CHAR(14),
    CONSTRAINT PK_NOTICIA PRIMARY KEY (TITULO, DATA),
    CONSTRAINT SK_NOTICIA UNIQUE (NOMEACONT, DATAACONT),
    CONSTRAINT FK1_NOTICIA FOREIGN KEY (NOMEACONT, DATAACONT) REFERENCES ACONTECIMENTO (NOME, DATA) ON DELETE CASCADE,
    CONSTRAINT FK2_NOTICIA FOREIGN KEY (REDATOR) REFERENCES FUNCIONARIO (CPF) ON DELETE SET NULL,
    CONSTRAINT FK3_NOTICIA FOREIGN KEY (PRODUTOR) REFERENCES FUNCIONARIO (CPF) ON DELETE SET NULL,
    CONSTRAINT CK_REDATOR CHECK (GET_CARGO(REDATOR) IN ('REDATOR')),
    CONSTRAINT CK_PRODUTOR CHECK (GET_CARGO(PRODUTOR) IN ('PRODUTOR'))
);
-- mesmo coisa acontece aqui. Demitir editor ou produtor não deve ocasionar em perda de conteúdo, acho.
-- coloquei o delete da FK1_NOTICIA como cascade, não vejo pq deletar acontecimento se n for pra remover tudo associado a ele.


CREATE TABLE FILMAGEMBRUTA (
    ID INT GENERATED ALWAYS AS IDENTITY,
    TITULONOTICIA VARCHAR(200) NOT NULL,
    DATANOTICIA DATE NOT NULL,
    NROFILMAGEM INT NOT NULL,
    DURACAOINICIAL INT,
    CONSTRAINT PK_FILMAGEMBRUTA PRIMARY KEY (ID),
    CONSTRAINT SK_FILMAGEMBRUTA UNIQUE (TITULONOTICIA, DATANOTICIA, NROFILMAGEM),
    CONSTRAINT FK_FILMAGEMBRUTA FOREIGN KEY (TITULONOTICIA, DATANOTICIA) REFERENCES NOTICIA (TITULO, DATA) ON DELETE CASCADE
);


CREATE TABLE FILMAGEMEDITADA (
    FILMBRUTA INT NOT NULL,
    NROEDICAO INT NOT NULL,
    DURACAOFINAL INT,
    EDITOR CHAR(14),
    CONSTRAINT PK_FILMAGEMEDITADA PRIMARY KEY (FILMBRUTA, NROEDICAO),
    CONSTRAINT FK1_FILMAGEMEDITADA FOREIGN KEY (FILMBRUTA) REFERENCES FILMAGEMBRUTA (ID) ON DELETE CASCADE,
    CONSTRAINT FK2_FILMAGEMEDITADA FOREIGN KEY (EDITOR) REFERENCES FUNCIONARIO (CPF) ON DELETE SET NULL,
    CONSTRAINT CK_EDITOR CHECK (GET_CARGO(EDITOR) IN ('EDITOR'))
);


CREATE TABLE EQUIPESDECAMPO (
    FILMBRUTA INT NOT NULL,
    AGENTECAMPO CHAR(14) NOT NULL,
    CONSTRAINT PK_EQUIPEDECAMPO PRIMARY KEY (FILMBRUTA, AGENTECAMPO),
    CONSTRAINT FK1_EQUIPEDECAMPO FOREIGN KEY (FILMBRUTA) REFERENCES FILMAGEMBRUTA (ID) ON DELETE CASCADE,
    CONSTRAINT FK2_EQUIPEDECAMPO FOREIGN KEY (AGENTECAMPO) REFERENCES AGENTE (CPF) ON DELETE CASCADE,
    CONSTRAINT CK_CAMPO CHECK (GET_CARGO(AGENTECAMPO) IN ('CAMERAMAN_C', 'AUXILIAR_C', 'REPORTER', 'MOTORISTA'))
);


CREATE TABLE EPISODIO (
    DATA DATE NOT NULL,
    DURACAO INT,
    CONSTRAINT PK_EPISODIO PRIMARY KEY (DATA)
);


CREATE TABLE BLOCO (
    EPISODIO DATE NOT NULL,
    NROBLOCO INT NOT NULL,
    CONSTRAINT PK_BLOCO PRIMARY KEY (EPISODIO, NROBLOCO),
    CONSTRAINT FK_BLOCO FOREIGN KEY (EPISODIO) REFERENCES EPISODIO (DATA) ON DELETE CASCADE
);


CREATE TABLE PERTENCE (
    EPISODIO DATE NOT NULL,
    NROBLOCO INT NOT NULL,
    FILMEDITADA INT NOT NULL,
    NROEDIC INT NOT NULL,
    HORA TIME,
    CONSTRAINT PK_PERTENCE PRIMARY KEY (EPISODIO, NROBLOCO, FILMEDITADA, NROEDIC),
    CONSTRAINT FK1_PERTENCE FOREIGN KEY (EPISODIO, NROBLOCO) REFERENCES BLOCO (EPISODIO, NROBLOCO) ON DELETE CASCADE,
    CONSTRAINT FK2_PERTENCE FOREIGN KEY (FILMEDITADA, NROEDIC) REFERENCES FILMAGEMEDITADA (FILMBRUTA, NROEDICAO) ON DELETE CASCADE
);
-- no doc ta como FILMBRUTA!

CREATE TABLE AUDIENCIA (
    DATA DATE NOT NULL,
    HORARIO TIME NOT NULL,
    IBOPE FLOAT,
    CONSTRAINT PK_AUDIENCIA PRIMARY KEY (DATA, HORARIO),
    CONSTRAINT FK_AUDIENCIA FOREIGN KEY (DATA) REFERENCES EPISODIO (DATA) ON DELETE CASCADE
);


CREATE TABLE PROPAGANDA (
    CNPJ CHAR(18) NOT NULL,
    NOMEPROPAGANDA VARCHAR(100) NOT NULL,
    DURACAO TIME,
    VALOR FLOAT,
    CONSTRAINT PK_PROPAGANDA PRIMARY KEY (CNPJ, NOMEPROPAGANDA),
    CONSTRAINT CK_CNPJ CHECK (CNPJ ~ '[0-9]{2}\.[0-9]{3}\.[0-9]{3}\/[0-9]{4}\-[0-9]{2}$')
);


CREATE TABLE PROPAGANDASEXIBIDAS (
    CNPJ CHAR(18) NOT NULL,
    NOMEPROPAGANDA VARCHAR(100) NOT NULL,
    EPISODIO DATE NOT NULL,
    NROBLOCO INT NOT NULL,
    HORARIO TIME NOT NULL,
    CONSTRAINT PK_PROPAGANDASEXIBIDAS PRIMARY KEY (EPISODIO, HORARIO),
    CONSTRAINT FK1_PROPAGANDASEXIBIDAS FOREIGN KEY (CNPJ, NOMEPROPAGANDA) REFERENCES PROPAGANDA (CNPJ, NOMEPROPAGANDA) ON DELETE CASCADE,
    CONSTRAINT FK2_PROPAGANDASEXIBIDAS FOREIGN KEY (EPISODIO, NROBLOCO) REFERENCES BLOCO (EPISODIO, NROBLOCO) ON DELETE CASCADE
);
-- essa aqui não tem not null nos esquema, mas acho que faz sentido colocar, n?


CREATE TABLE EQUIPESDEESTUDIO (
    EPISODIO DATE NOT NULL,
    AGENTEESTUDIO CHAR(14) NOT NULL,
    CONSTRAINT PK_EQUIPESDEESTUDIO PRIMARY KEY (EPISODIO, AGENTEESTUDIO),
    CONSTRAINT FK1_EQUIPESDEESTUDIO FOREIGN KEY (EPISODIO) REFERENCES EPISODIO (DATA) ON DELETE CASCADE,
    CONSTRAINT FK2_EQUIPESDEESTUDIO FOREIGN KEY (AGENTEESTUDIO) REFERENCES AGENTE (CPF) ON DELETE CASCADE,
    CONSTRAINT CK_ESTUDIO CHECK (GET_CARGO(AGENTEESTUDIO) IN ('CAMERAMAN_E', 'AUXILIAR_E', 'APRESENTADOR'))
);